'use strict';

const defaultSettings = {
  brand: {
    name: 'My Store',
    currency: 'MAD',
    language: 'ar',
    timezone: 'Africa/Casablanca',
    phone: '',
    email: '',
    address: '',
    logo: '',
    instagram: '',
    facebook: '',
    tiktok: '',
    whatsapp: '',
  },
  social: {
    whatsapp:  { connected: false, pageId: '', accessToken: '', name: '', phoneNumber: '', autoPublish: false },
    facebook:  { connected: false, pageId: '', accessToken: '', name: '', autoPublish: false },
    instagram: { connected: false, pageId: '', accessToken: '', name: '', autoPublish: false },
    tiktok:    { connected: false, pageId: '', accessToken: '', name: '', autoPublish: false },
    openai:    { connected: false, apiKey: '', model: 'gpt-4o-mini' },
    gemini:    { connected: false, apiKey: '' },
  },
  ai: {
    provider: 'openai',
    apiKey: '',
    geminiKey: '',
    model: 'gpt-4o-mini',
    personality: 'Moroccan Seller',
    tone: 'Friendly',
    language: 'Darija',
    replyDelay: 2,
    humanSimulation: true,
    autoDiscount: true,
    maxDiscount: 15,
    temperature: 0.7,
    darijaMode: true,
    contextMemory: 10,
    systemPrompt: 'أنت مساعد بيع ذكي لمتجر مغربي. تحدث بالدارجة المغربية بأسلوب ودود واحترافي. ساعد الزبائن في الطلب والاستفسار عن المنتجات.',
  },
  delivery: {
    providers: [],
    defaultProvider: '',
    autoSendOnApproval: false,
    notifyCustomerOnShip: true,
    trackingUrlTemplate: '',
    defaultCost: 30,
  },
  products: {
    autoSku: true,
    skuPrefix: 'PRD',
    lowStockAlert: 5,
    taxRate: 0,
    autoPublishOnCreate: false,
    defaultSizes: ['S', 'M', 'L', 'XL', 'XXL'],
    defaultColors: ['أسود', 'أبيض', 'أحمر', 'أزرق', 'أخضر', 'بيج'],
    categories: ['ملابس رجالية', 'ملابس نسائية', 'أحذية', 'إكسسوارات', 'ملابس أطفال', 'منزل وديكور'],
  },
  notifications: {
    newOrder: true,
    orderConfirm: true,
    shipNotify: true,
    promoBlast: false,
    whatsappEnabled: false,
    emailEnabled: false,
  },
  deliveryCosts: {
    'الدار البيضاء': 20, 'casablanca': 20, 'الرباط': 25, 'rabat': 25,
    'فاس': 30, 'مراكش': 30, 'طنجة': 35, 'أكادير': 35,
    'مكناس': 30, 'وجدة': 40, 'سلا': 25, 'تطوان': 35,
    'القنيطرة': 30, 'الجديدة': 35, 'بني ملال': 40, 'default': 40,
  },
  catalog: {
    public: false,
    showPrices: true,
    showStock: false,
    customUrl: '',
    welcomeMessage: 'مرحباً بكم في متجرنا! 🛍️',
    backgroundColor: '#06060f',
  },
  onboardingDone: false,
};

module.exports = { defaultSettings };
